services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food_backend
    ports:
      - "42069:42069"
    env_file:
      - ./backend/.env
    networks:
      - food-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food_frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://backend:42069/api/v1
    depends_on:
      - backend
    networks:
      - food-network
    restart: unless-stopped
    
  db:
    image: postgres:16
    container_name: food_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "postgres"
    networks:
      - food-network
    volumes:
     - "pgdata:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  pgdata:

networks:
  food-network:
    driver: bridge
